[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.build]
cmds = ["chmod +x mvnw && ./mvnw clean package -DskipTests"]

[start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/pastebin-lite-1.0.0.jar"