[phases.setup]
nixPkgs = ["...", "maven", "jdk21"]

[phases.build]
cmds = ["./mvnw clean package -DskipTests"]

[start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/pastebin-lite-1.0.0.jar"
